import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  pageShell: {
    minHeight: "100vh",
    display: "grid",
    gridTemplateColumns: "1.1fr 0.9fr",
    gap: "28px",
    padding: "32px",
    position: "relative",
    overflow: "hidden",
    backgroundImage:
      "radial-gradient(circle at top left, rgba(194, 92, 52, 0.18), transparent 28%), linear-gradient(135deg, #f6efdf 0%, #f1dfc5 45%, #e7d3ba 100%)",
    "@media (max-width: 980px)": {
      gridTemplateColumns: "1fr",
      padding: "20px",
    },
  },
  pageShellSingle: {
    gridTemplateColumns: "1fr",
  },
  backgroundGlow: {
    position: "absolute",
    borderRadius: "999px",
    filter: "blur(30px)",
    opacity: 0.65,
    pointerEvents: "none",
  },
  glowTop: {
    width: "280px",
    height: "280px",
    top: "-100px",
    right: "12%",
    backgroundColor: "rgba(184, 63, 34, 0.22)",
  },
  glowBottom: {
    width: "320px",
    height: "320px",
    bottom: "-140px",
    left: "-80px",
    backgroundColor: "rgba(46, 122, 108, 0.16)",
  },
  heroPanel: {
    position: "relative",
    zIndex: 1,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: "20px",
    padding: "28px 12px",
  },
  heroPanelCompact: {
    minHeight: "22vh",
    justifyContent: "flex-start",
    paddingBottom: 0,
  },
  kicker: {
    width: "fit-content",
    padding: "10px 14px",
    borderRadius: "999px",
    backgroundColor: "rgba(27, 26, 23, 0.08)",
    color: "#4f3225",
    fontSize: "0.78rem",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.12em",
  },
  heroTitle: {
    fontSize: "clamp(3rem, 7vw, 5.5rem)",
    lineHeight: 0.95,
    maxWidth: "10ch",
    color: "#241811",
  },
  heroTitleCompact: {
    fontSize: "clamp(2.4rem, 6vw, 4rem)",
    maxWidth: "12ch",
  },
  heroCopy: {
    maxWidth: "58ch",
    color: "#5f4a3d",
    fontSize: "1.05rem",
    lineHeight: 1.7,
  },
  heroBadgeRow: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "14px",
    marginTop: "10px",
    "@media (max-width: 760px)": {
      gridTemplateColumns: "1fr",
    },
  },
  badge: {
    padding: "16px",
    borderRadius: "22px",
    backgroundColor: "rgba(255, 255, 255, 0.48)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(36, 24, 17, 0.08)",
    backdropFilter: "blur(16px)",
  },
  badgeLabel: {
    display: "block",
    color: "#74574a",
    fontSize: "0.82rem",
    marginBottom: "8px",
  },
  badgeValue: {
    color: "#241811",
    fontSize: "1.05rem",
  },
  surfaceCard: {
    position: "relative",
    zIndex: 1,
    borderRadius: "32px",
    padding: "28px",
    backgroundColor: "rgba(255, 250, 244, 0.82)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(36, 24, 17, 0.1)",
    boxShadow: "0 24px 80px rgba(74, 44, 28, 0.12)",
    backdropFilter: "blur(20px)",
    display: "flex",
    flexDirection: "column",
    gap: "18px",
  },
  surfaceWide: {
    maxWidth: "1120px",
    width: "100%",
    justifySelf: "center",
  },
  surfaceHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: "16px",
    alignItems: "center",
  },
  eyebrow: {
    color: "#8b6b5d",
    fontSize: "0.76rem",
    textTransform: "uppercase",
    letterSpacing: "0.12em",
    marginBottom: "8px",
    fontWeight: 700,
  },
  surfaceTitle: {
    fontSize: "2rem",
    color: "#211611",
  },
  notice: {
    color: "#6a4f41",
    backgroundColor: "#f7ecdf",
    borderRadius: "18px",
    padding: "14px 16px",
    fontSize: "0.96rem",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  formTitle: {
    fontSize: "1.45rem",
    color: "#241811",
    marginBottom: "6px",
  },
  formSubtitle: {
    color: "#74574a",
    lineHeight: 1.6,
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  fieldLabel: {
    color: "#4a3025",
    fontWeight: 600,
    fontSize: "0.92rem",
  },
  input: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(73, 50, 37, 0.14)",
    borderRadius: "16px",
    backgroundColor: "rgba(255, 255, 255, 0.92)",
    padding: "14px 16px",
    fontSize: "0.98rem",
    color: "#211611",
    outline: "none",
    transitionDuration: "180ms",
    transitionProperty: "border-color, box-shadow, transform",
    ":focus": {
      borderColor: "#b85d37",
      boxShadow: "0 0 0 4px rgba(184, 93, 55, 0.12)",
      transform: "translateY(-1px)",
    },
  },
  primaryButton: {
    borderWidth: 0,
    borderRadius: "16px",
    padding: "14px 18px",
    backgroundColor: "#b85d37",
    color: "#fff8f2",
    fontSize: "1rem",
    fontWeight: 700,
    cursor: "pointer",
    transitionDuration: "180ms",
    transitionProperty: "transform, box-shadow, background-color, opacity",
    boxShadow: "0 14px 28px rgba(184, 93, 55, 0.22)",
    ":hover": {
      transform: "translateY(-1px)",
      backgroundColor: "#a84f2c",
    },
    ":disabled": {
      cursor: "not-allowed",
      opacity: 0.7,
    },
  },
  secondaryButton: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(36, 24, 17, 0.12)",
    borderRadius: "14px",
    padding: "12px 14px",
    backgroundColor: "transparent",
    color: "#3e2a20",
    cursor: "pointer",
    fontWeight: 600,
  },
  smallButton: {
    padding: "10px 12px",
  },
  formFooter: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexWrap: "wrap",
  },
  footerText: {
    color: "#74574a",
  },
  inlineButton: {
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "#a84f2c",
    fontWeight: 700,
    cursor: "pointer",
    padding: 0,
  },
  ghostButton: {
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "#5b7f78",
    fontWeight: 700,
    cursor: "pointer",
    width: "fit-content",
    padding: 0,
  },
  dashboardStack: {
    display: "flex",
    flexDirection: "column",
    gap: "18px",
  },
  dashboardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "16px",
    flexWrap: "wrap",
  },
  dashboardTitle: {
    fontSize: "1.5rem",
    color: "#241811",
  },
  dashboardSubtitle: {
    color: "#74574a",
  },
  statusPill: {
    padding: "10px 14px",
    borderRadius: "999px",
    backgroundColor: "rgba(57, 126, 111, 0.12)",
    color: "#25584d",
    fontWeight: 700,
    fontSize: "0.82rem",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
  },
  dashboardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "16px",
    "@media (max-width: 760px)": {
      gridTemplateColumns: "1fr",
    },
  },
  dashboardCard: {
    padding: "20px",
    borderRadius: "24px",
    backgroundColor: "#fffdf8",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(36, 24, 17, 0.08)",
    boxShadow: "0 12px 32px rgba(74, 44, 28, 0.08)",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  cardTall: {
    gridRow: "span 2",
    "@media (max-width: 760px)": {
      gridRow: "span 1",
    },
  },
  cardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "12px",
  },
  cardTitle: {
    fontSize: "1.1rem",
    color: "#241811",
  },
  cardChip: {
    padding: "8px 10px",
    borderRadius: "999px",
    backgroundColor: "#f4ebde",
    color: "#7a5a49",
    fontSize: "0.78rem",
    fontWeight: 700,
  },
  metricList: {
    display: "grid",
    gap: "12px",
  },
  metricItem: {
    padding: "14px",
    borderRadius: "18px",
    backgroundColor: "#f9f3ea",
    display: "grid",
    gap: "6px",
  },
  metricLabel: {
    color: "#74574a",
    fontSize: "0.88rem",
  },
  metricValue: {
    color: "#241811",
    fontSize: "2rem",
    lineHeight: 1,
  },
  metricDetail: {
    color: "#8c6855",
  },
  feed: {
    display: "grid",
    gap: "14px",
  },
  feedItem: {
    display: "grid",
    gridTemplateColumns: "12px 1fr",
    gap: "12px",
    alignItems: "start",
  },
  feedDot: {
    width: "12px",
    height: "12px",
    borderRadius: "999px",
    marginTop: "6px",
    backgroundColor: "#5b7f78",
  },
  feedDotAccent: {
    backgroundColor: "#b85d37",
  },
  feedDotWarning: {
    backgroundColor: "#c1882f",
  },
  feedTitle: {
    color: "#30211a",
    lineHeight: 1.5,
  },
  feedTime: {
    color: "#8c6855",
    marginTop: "4px",
    fontSize: "0.9rem",
  },
  teamList: {
    display: "grid",
    gap: "14px",
  },
  teamItem: {
    display: "grid",
    gridTemplateColumns: "48px 1fr",
    gap: "12px",
    alignItems: "start",
  },
  avatar: {
    width: "48px",
    height: "48px",
    borderRadius: "16px",
    display: "grid",
    placeItems: "center",
    backgroundColor: "#f0dfcf",
    color: "#6b412f",
    fontWeight: 800,
  },
  teamName: {
    color: "#2d1f18",
    fontWeight: 700,
  },
  teamRole: {
    color: "#8c6855",
    marginTop: "4px",
    fontSize: "0.92rem",
  },
  teamStatus: {
    color: "#496d65",
    marginTop: "6px",
    fontSize: "0.92rem",
  },
  loaderCard: {
    minHeight: "260px",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
  },
});
